### ISSUE TITLE
Adding total number of members in the fnotch output results

### ISSUE THREAD

**Issue by mschwamb** [michaelaye/planet4#19]
To be able to select out clustering that might be noise, I need to know how many total members are jointly in the fnotch. I can't find an east way to go back to the individual fan and blotch catalogs you generate. @michaelaye  can you please output the sum of the members of the fan+ blotch in your fnotch output? thanks

**Comment by michaelaye** [comment]
Just for my understanding, is this different from #18? And, considering that we agreed not to artificially combine markings of fans and blotches of fnotches, shouldn't I rather keep track of both the number of cluster members of the mean fan AND the mean blotch that make up the fnotch instead of just the sum of both?

**Comment by mschwamb** [comment]
I forgot in the title for that other ticket I mentioned outputting this. 

I want for each individual source which I'm taking as a fnotch - so you can save and report the total number of fan markings and total number of blotch markings that went into it or the total, since the fnotch scores gives the relative frequency of one to the other.

**Comment by michaelaye** [comment]
Fixed by a7d95fd0bd8600b40f796fce7e9c840de494ea72
